import Link from "next/link";
import { BrandMark } from "./brand-mark";

const footerLinks = [
  ["Focus Run", "/focus"],
  ["Classic Five", "/play"],
  ["How to play", "/how-to-play"],
  ["Pattern lab", "/categories"],
  ["About", "/about"],
  ["Privacy", "/privacy"],
  ["Terms", "/terms"],
  ["Contact", "/contact"],
] as const;

export function SiteFooter() {
  return (
    <footer className="site-footer">
      <div className="shell site-footer__grid">
        <div className="site-footer__brand">
          <BrandMark />
          <p>One anomaly. Three focus charges. Infinite deterministic boards.</p>
        </div>
        <nav className="footer-nav" aria-label="Footer navigation">
          {footerLinks.map(([label, href]) => (
            <Link href={href} key={href}>
              {label}
            </Link>
          ))}
        </nav>
      </div>
      <div className="shell site-footer__legal">
        <span>© {new Date().getUTCFullYear()} One Pixel Off</span>
        <span>Generated by code, not by AI.</span>
      </div>
    </footer>
  );
}
